
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '../styles/home.module.scss'
import Image from 'next/image'
import logoImg from '../../public/logo-transparente.png'
import { Input } from '@/components/UI/Input'
import { Button } from '@/components/UI/Button'
import Link from 'next/link'





const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Faça seu Login - Oficina do Print</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.containerCenter}>
        <Image src={logoImg} alt="logo oficina do print" />

        <div className={styles.login}>
          <form className={styles.form}>
            <Input
              placeholder='Digite seu email'
              type="text"
            />
            <Input
              placeholder='Digite seu senha'
              type="password"
            />

            <Button
              type="submit"
              loading={false}
            >
              Acessar
            </Button>

          </form>
          <Link href='/signup'>
            <h1>Não tem uma conta? Cadastre-se!</h1>
          </Link>

        </div>
      </div>

    </>
  )
}
