
import { useContext, FormEvent, useState } from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '../styles/home.module.scss'
import Image from 'next/image'
import logoImg from '../../public/logo-transparente.png'
import { Input } from '@/components/UI/Input'
import { Button } from '@/components/UI/Button'
import Link from 'next/link'
import { AuthContext } from '@/contexts/AuthContext'





const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { signIn } = useContext(AuthContext)

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const [loading, setLoading] = useState(false);

  async function handleLogin(event: FormEvent) {
    event.preventDefault()

    let data = {
      email,
      password
    }
    await signIn(data)
  }

  return (
    <>
      <Head>
        <title>Faça seu Login - Oficina do Print</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.containerCenter}>
        <Image src={logoImg} alt="logo oficina do print" />

        <div className={styles.login}>
          <form className={styles.form} onSubmit={handleLogin}>
            <Input
              placeholder='Digite seu email'
              type="text"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
            <Input
              placeholder='Digite seu senha'
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />

            <Button
              type="submit"
              loading={false}
            >
              Acessar
            </Button>

          </form>
          <Link href='/signup'>
            <h3>Não tem uma conta? Cadastre-se!</h3>
          </Link>

        </div>
      </div>

    </>
  )
}
